---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
    - net-tools
    - git
  when: ansible_facts['os_family']=="Debian"

- name: copy the content
  copy:
    content: "lets begin it first"
    dest: "/var/www/html/index.html"
  notify:
    - manage services
    
